module AbsBNF where

-- Haskell module generated by the BNF converter


newtype NonTerminal = NonTerminal String deriving (Eq,Ord,Show)
data Syntax =
   SyntaxNil
 | SyntaxCons Rule Syntax
  deriving (Eq,Ord,Show)

data Rule =
   Rule NonTerminal Expression
  deriving (Eq,Ord,Show)

data Expression =
   ExpressionList List
 | ExpressionOpt List Expression
  deriving (Eq,Ord,Show)

data List =
   ListOne Term
 | ListCons Term List
  deriving (Eq,Ord,Show)

data Term =
   Literal String
 | NonTerm NonTerminal
  deriving (Eq,Ord,Show)

